$modelname "weapons\arc9\uplp\ar15_rs.mdl"

$cdmaterials "models\weapons\arc9\uplp"

$bodygroup "body"
{
	studio "rs_1.smd" // 0
	studio "rs_1f.smd" // 1
	studio "rs_2.smd" // 2
	studio "rs_2f.smd" // 3
	studio "rs_idk.smd" // 4
	studio "rs_idkf.smd" // 5
	studio "rs_m4.smd" // 6
	studio "rs_m4f.smd" // 7
	studio "rs_mbus.smd" // 8
	studio "rs_mbusf.smd" // 9
	studio "rs_sw.smd" // a 10
	studio "rs_swf.smd" // b 11
	studio "rs_carry.smd" // c 12
}

$sequence "idle" {
	"rs_1.smd"
}