$modelname "weapons\arc9\uplp\ar15_stocks.mdl"

$cdmaterials "models\weapons\arc9\uplp"

$bodygroup "body"
{
	studio "stock_m4.smd" // 0
	studio "stock_m4fat.smd" // 1
	studio "stock_m16.smd" // 2
	studio "stock_modern.smd" // 3
	studio "stock_tac.smd" // 4
	studio "stock_sniper.smd" // 5
	studio "stock_veryheavy.smd" // 6
	studio "stock_416.smd" // 7
	studio "stock_ak12.smd" // 8
}

$sequence "idle" {
	"stock_ak12.smd"
}