$modelname "weapons\arc9\uplp\ak_grips.mdl"

$cdmaterials "models\weapons\arc9\uplp"

$bodygroup "grip" { // 4
	studio "grip std.smd" // 0
	studio "grip bak.smd" // 1
	studio "grip old.smd" // 2
	studio "grip tac.smd" // 3
	studio "grip tapco.smd" // 4
	studio "grip vityaz.smd" // 5
	studio "grip beryl.smd" // 6
	studio "grip 12.smd" // 7
	studio "grip 12 evo.smd" // 8

	studio "grip vepr.smd" // 9
	studio "grip agr.smd" // 9
}  

$sequence "idle" {
	"grip std.smd"
}