$modelname "weapons\arc9\uplp\ak_muzzles.mdl"

$cdmaterials "models\weapons\arc9\uplp"

$bodygroup "body"
{
	studio "mz std.smd" // 0
	studio "mz akm.smd" // 1
	studio "mz compact.smd" // 2
	studio "mz rpk.smd" // 3
	studio "mz vityaz.smd" // 4
	studio "mz bizon.smd" // 5
	studio "mz 12.smd" // 6
	studio "mz 19.smd" // 7
	studio "mz rpk16.smd" // 8
	studio "silencer.smd" // 9
}

$sequence "idle" {
	"mz std.smd"
}