$modelname "weapons\arc9\uplp\ak_muzzles.mdl"

$cdmaterials "models\weapons\arc9\uplp"

$bodygroup "body"
{
	studio "mz std.smd" // 0
	studio "mz akm.smd" // 0
	studio "mz compact.smd" // 0
	studio "mz rpk.smd" // 0
	studio "mz vityaz.smd" // 0
	studio "mz bizon.smd" // 0
	studio "mz 12.smd" // 0
	studio "mz 19.smd" // 0
	studio "mz rpk16.smd" // 0
	studio "silencer.smd" // 0
}

$sequence "idle" {
	"mz std.smd"
}